In [1]:
import torch

In [2]:
x = torch.tensor(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    dtype=torch.float32
)

In [3]:
print(x)
print(x.size())
print(x+1)
print(x*x)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])
tensor([[2., 3.],
        [4., 5.],
        [6., 7.]])
tensor([[ 1.,  4.],
        [ 9., 16.],
        [25., 36.]])


In [4]:
print(x.T)
print(x.T.mm(x))  # Matricu reizināšana

tensor([[1., 3., 5.],
        [2., 4., 6.]])
tensor([[35., 44.],
        [44., 56.]])


In [5]:
print(torch.rand(3,2))
print(torch.ones(3,2))
print(torch.zeros(3,2))

tensor([[0.7154, 0.9062],
        [0.7143, 0.3768],
        [0.7727, 0.4379]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [6]:
ievaddati = [[0, 0], [0, 1], [1, 0], [1, 1]] # Visas 4 kombinācijas
rezultāts_or = [x[0] or x[1] for x in ievaddati]
rezultāts_and = [x[0] and x[1] for x in ievaddati]
rezultāts_xor = [x[0] ^ x[1] for x in ievaddati]
rezultāts_xor
# Šie ir python saraksti nevis pytorch tenzori!

[0, 1, 1, 0]

In [7]:
ievaddati = torch.tensor(ievaddati, dtype=torch.float32)
rezultāts_or = torch.tensor(rezultāts_or, dtype=torch.float32)
rezultāts_and = torch.tensor(rezultāts_and, dtype=torch.float32)
rezultāts_xor = torch.tensor(rezultāts_xor, dtype=torch.float32)
ievaddati

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

In [8]:
b = torch.tensor(-5.0)
w = torch.tensor([10.0, 10.0])
w

tensor([10., 10.])

In [9]:
for ievads, cerētais in zip(ievaddati, rezultāts_or):
  print(f'No {ievads} gribam dabūt {cerētais}')

No tensor([0., 0.]) gribam dabūt 0.0
No tensor([0., 1.]) gribam dabūt 1.0
No tensor([1., 0.]) gribam dabūt 1.0
No tensor([1., 1.]) gribam dabūt 1.0


In [10]:
for ievads, cerētais in zip(ievaddati, rezultāts_or):
    z = b + w @ ievads
    rezultāts = torch.sigmoid(z)
    print(z, rezultāts)

tensor(-5.) tensor(0.0067)
tensor(5.) tensor(0.9933)
tensor(5.) tensor(0.9933)
tensor(15.) tensor(1.0000)


In [11]:
sliktums = 0
for ievads, cerētais in zip(ievaddati, rezultāts_or):
    z = b + w @ ievads
    rezultāts = torch.sigmoid(z)
    kļūda = torch.square(rezultāts-cerētais)
    sliktums += kļūda
    print(f'No {ievads} gribējām dabūt {cerētais}, sanāca {rezultāts:.5f}')
print(f'No visiem piemēriem vidējā kvadrātiskā kļūda ir {sliktums/len(ievaddati):.5f}')

No tensor([0., 0.]) gribējām dabūt 0.0, sanāca 0.00669
No tensor([0., 1.]) gribējām dabūt 1.0, sanāca 0.99331
No tensor([1., 0.]) gribējām dabūt 1.0, sanāca 0.99331
No tensor([1., 1.]) gribējām dabūt 1.0, sanāca 1.00000
No visiem piemēriem vidējā kvadrātiskā kļūda ir 0.00003


In [12]:
sliktums = 0
for ievads, cerētais in zip(ievaddati, rezultāts_and):
    z = b + w @ ievads
    rezultāts = torch.sigmoid(z)
    kļūda = torch.square(rezultāts-cerētais)
    sliktums += kļūda
    print(f'No {ievads} gribējām dabūt {cerētais}, sanāca {rezultāts:.5f}')
print(f'No visiem piemēriem vidējā kvadrātiskā kļūda ir {sliktums/len(ievaddati):.5f}')

No tensor([0., 0.]) gribējām dabūt 0.0, sanāca 0.00669
No tensor([0., 1.]) gribējām dabūt 0.0, sanāca 0.99331
No tensor([1., 0.]) gribējām dabūt 0.0, sanāca 0.99331
No tensor([1., 1.]) gribējām dabūt 1.0, sanāca 1.00000
No visiem piemēriem vidējā kvadrātiskā kļūda ir 0.49334


In [13]:
b = torch.tensor(-5.0, requires_grad = True)
w = torch.tensor([10.0, 10.0], requires_grad = True)
sliktums = torch.tensor(0.0)
for ievads, cerētais in zip(ievaddati, rezultāts_and):
    z = b + w @ ievads
    rezultāts = torch.sigmoid(z)
    kļūda = torch.square(rezultāts-cerētais)
    sliktums += kļūda
    print(f'No {ievads} gribējām dabūt {cerētais}, sanāca {rezultāts:.5f}')
print(f'No visiem piemēriem vidējā kvadrātiskā kļūda ir {sliktums/len(ievaddati):.5f}')
sliktums.backward()
print(b.grad)
print(w.grad)

No tensor([0., 0.]) gribējām dabūt 0.0, sanāca 0.00669
No tensor([0., 1.]) gribējām dabūt 0.0, sanāca 0.99331
No tensor([1., 0.]) gribējām dabūt 0.0, sanāca 0.99331
No tensor([1., 1.]) gribējām dabūt 1.0, sanāca 1.00000
No visiem piemēriem vidējā kvadrātiskā kļūda ir 0.49334
tensor(0.0265)
tensor([0.0132, 0.0132])


In [51]:
import random

b = torch.tensor(random.randint(-15,15), requires_grad = True, dtype=torch.float32)
w = torch.tensor([random.randint(-15,15), random.randint(-15,15)], requires_grad = True, dtype=torch.float32)

for ievads, cerētais in zip(ievaddati, rezultāts_and):
    z = b + w @ ievads
    rezultāts = torch.sigmoid(z)
    kļūda = torch.square(rezultāts-cerētais)
    sliktums += kļūda
    print(f'No {ievads} gribējām dabūt {cerētais}, sanāca {rezultāts:.5f}')
print(f'No visiem piemēriem vidējā kvadrātiskā kļūda ir {sliktums/len(ievaddati):.5f} ar b: {b} un w: {w}')

for i in range(50000):
    sliktums = torch.tensor(0.0)
    for ievads, cerētais in zip(ievaddati, rezultāts_and):
        z = b + w @ ievads
        rezultāts = torch.sigmoid(z)
        kļūda = torch.square(rezultāts-cerētais)
        sliktums += kļūda
        # print(f'No {ievads} gribējām dabūt {cerētais}, sanāca {rezultāts:.5f}')
    # print(f'No visiem piemēriem vidējā kvadrātiskā kļūda ir {sliktums/len(ievaddati):.5f}')
    sliktums.backward()

    with torch.no_grad():
        b -= 0.25 * b.grad
        w -= 0.25 * w.grad

        b.grad = None
        w.grad = None

sliktums = torch.tensor(0.0)
for ievads, cerētais in zip(ievaddati, rezultāts_and):
    z = b + w @ ievads
    rezultāts = torch.sigmoid(z)
    kļūda = torch.square(rezultāts-cerētais)
    sliktums += kļūda
    print(f'No {ievads} gribējām dabūt {cerētais}, sanāca {rezultāts:.5f}')
print(f'No visiem piemēriem vidējā kvadrātiskā kļūda ir {sliktums/len(ievaddati):.5f} ar b: {b} un w: {w}')


No tensor([0., 0.]) gribējām dabūt 0.0, sanāca 1.00000
No tensor([0., 1.]) gribējām dabūt 0.0, sanāca 0.99753
No tensor([1., 0.]) gribējām dabūt 0.0, sanāca 0.99999
No tensor([1., 1.]) gribējām dabūt 1.0, sanāca 0.95257
No visiem piemēriem vidējā kvadrātiskā kļūda ir 0.74943 ar b: 15.0 un w: tensor([-3., -9.], requires_grad=True)
No tensor([0., 0.]) gribējām dabūt 0.0, sanāca 0.99932
No tensor([0., 1.]) gribējām dabūt 0.0, sanāca 0.00233
No tensor([1., 0.]) gribējām dabūt 0.0, sanāca 1.00000
No tensor([1., 1.]) gribējām dabūt 1.0, sanāca 0.98734
No visiem piemēriem vidējā kvadrātiskā kļūda ir 0.49970 ar b: 7.299981594085693 un w: tensor([ 10.4144, -13.3575], requires_grad=True)
